/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;

import javax.swing.ImageIcon;

/**
 *
 * @author Oskr
 */
public class AhorcadoForm extends javax.swing.JFrame {

    /**
     * Creates new form AhorcadoForm
     */
    String palabra_secreta = "puto";
    char letras_encontradas[] = new char [palabra_secreta.length()];
    int fallos = 0;
    public AhorcadoForm() {
        initComponents();
        for(int i=0;i<palabra_secreta.length();i++)
        {
            letras_encontradas[i]='_';
        }
        
        String palabra_visible = "";
        for(int i=0;i<letras_encontradas.length;i++)
        {
            palabra_visible+=letras_encontradas[i]+" ";
        }
        
        lbl_palabra.setText(palabra_visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ahorcado = new javax.swing.JLabel();
        lbl_palabra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        tf_letra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        lbl_ahorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/1_360.png"))); // NOI18N

        lbl_palabra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_palabra.setText("_ _ _ _ _ _ _");

        jLabel1.setText("Ingresar una Letra: ");

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingresarMousePressed(evt);
            }
        });

        tf_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_letraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_ahorcado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_palabra)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ingresar)
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_ahorcado)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_ingresar)
                    .addComponent(tf_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_letraActionPerformed

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void btn_ingresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMousePressed
        char letra = tf_letra.getText().charAt(0);
        boolean letra_encontrada = false;
        for(int i=0;i<palabra_secreta.length();i++){
            if (palabra_secreta.charAt(i)==letra){
                letras_encontradas[i]=letra;
                letra_encontrada = true;
            }
        }
        if (!letra_encontrada){
            fallos++;
            if (fallos<=4){
                lbl_ahorcado.setIcon(new ImageIcon("/Users/Oskr/Desktop/JAVA/NETBEANS/Ahorcado/src/ahorcado/Imagenes/"+fallos+".png"));
            }else{
                lbl_ahorcado.setText("Has perdido");
            }
            
        }
        
        String palabra_visible = "";
        boolean gano = true;
        for(int i=0;i<letras_encontradas.length;i++)
        {
            palabra_visible+=letras_encontradas[i]+" ";
            
            if(letras_encontradas[i]=='_'){
                gano = false;
            }
        }
        
        lbl_palabra.setText(palabra_visible);
        
        if(gano){
            lbl_ahorcado.setText("El jugador ha ganado");
        }
        
        tf_letra.setText("");
    }//GEN-LAST:event_btn_ingresarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AhorcadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AhorcadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AhorcadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AhorcadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AhorcadoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_ahorcado;
    private javax.swing.JLabel lbl_palabra;
    private javax.swing.JTextField tf_letra;
    // End of variables declaration//GEN-END:variables
}
